#!/usr/bin/env bash
# vim: autoindent noexpandtab
set -e
#set -u
#set -o pipefail
set -x

# APT but only for fonts
# alex@aiei.ch
#
# selfupdate=https://raw.githubusercontent.com/alexmyczko/fnt/main/fnt

#FNTDATA="${FNTDATA:-/tmp}"
FNTDATA="${HOME}/.fnt"
PACKAGES="${FNTDATA}/Packages.xz"
# debian sid index
#INDEX="http://ftp.ch.debian.org/debian/dists/sid/main/binary-all/Packages.xz"
MIRROR="https://deb.debian.org/debian"
INDEX="${MIRROR}/dists/sid/main/binary-all/Packages.xz"
# google fonts index
GINDEX="http://bananas.debian.net/debian/google-fonts/fonts-main"

if ! command -v uname &>/dev/null; then
	s="Windows"
else
	s=$(uname -s)
fi

# Pipelines
pipe_download(){
	local PIPEFILE
	PIPEDIR="$(mktemp -d)"
	PIPEFILE="${1%%*/}"
	if test -z "${PIPEFILE}"; then PIPEFILE=index; fi
	chmod go-rwx "${PIPEDIR}"
	#trap 'rm -rf -- "$PIPEDIR"' EXIT
	download "$1" "$PIPEDIR/$PIPEFILE"
	cat "$PIPEDIR/$PIPEFILE"
}

download() {
	# shellcheck disable=SC2086
	local URL LOPTS HTTP_PROXY
	URL="$1"
	if test -z "${1##*.deb}"; then
		if test -r /etc/debian_version; then
			#eval "$(apt-config shell HTTP_PROXY Acquire::http::Proxy)"
			HTTP_PROXY=$(auto-apt-proxy 2>/dev/null)
			#HTTP_PROXY=${AUTO_APT:="$HTTP_PROXY"}
			if test -n "$HTTP_PROXY"; then
				# shellcheck disable=SC2086,SC2089
				LOPTS=" -o Acquire::http::Proxy=\"$HTTP_PROXY\""
				URL=${URL/https:/http:\//}
			fi
		fi
		if /usr/bin/which /usr/lib/apt/apt-helper>/dev/null
		then
			# shellcheck disable=SC2090,SC2086
			/usr/lib/apt/apt-helper $LOPTS download-file "$URL" "$2" >/dev/null
			return
		fi
	fi
	if /usr/bin/which fetch>/dev/null
	then
		fetch -q -o "$2" "$URL"
	elif /usr/bin/which curl>/dev/null
	then
		curl -g -L -s -o "$2" "$URL"
	elif /usr/bin/which wget>/dev/null
	then
		wget -q -O "$URL" "$2"
	else
		print "ERROR: neither apt-helper, wget, curl nor fetch is installed" >&2
		exit 70
	fi
}

deb_handler() {
	# retrieve font from debian mirror and store infos for removal
	TMPDIR="$(mktemp -d)"
	chmod go-rwx "${TMPDIR}"
	trap 'rm -rf -- "$TMPDIR"' EXIT
	PIT="${TMPDIR}/extract"
	mkdir -m go-rwx "${PIT}" || { echo "Couldn't eat tartar." ; exit 1 ; }
	NAME="$1"
	INFOS="$(unxz -c "${PACKAGES}" | awk "/^Package: ${NAME}$/,/^$/" | awk '/^(Version|Installed-Size|Filename|Size|MD5sum): /')"
	VER="$(awk '/^Version: /{print$2}' <<< "$INFOS")"
	INSTSIZE="$(awk '/^Installed-Size: /{print$2}' <<< "$INFOS")"
	DOWNSIZE="$(awk '/^Size: /{print$2}' <<< "$INFOS")"
	FPATH="$(awk '/^Filename: /{print$2}' <<< "$INFOS")"
	FNAME="$(basename "$FPATH")"
	MD5SUM="$(awk '/^MD5sum: /{print$2}' <<< "$INFOS") ${FNAME}"
	echo "Installing ${NAME} ${VER} [${DOWNSIZE} ${INSTSIZE}000 ${MIRROR}/${FPATH}]..."
	cd "${TMPDIR}" || { echo "Couldn't cd into ${TMPDIR}" ; exit 1 ; }
	test -z "$(download "${MIRROR}/${FPATH}" "${TMPDIR}/$FNAME")" || { echo "Couldn't retrieve file." ; exit 1 ; }
	echo "${MD5SUM}" > "${TMPDIR}/${FNAME}.md5"
	if ${md5} -c "${TMPDIR}/${FNAME}.md5" >/dev/null; then
		DATA="$(ar t "$TMPDIR/$FNAME" | grep '^data\.tar')"
		mkdir -p "${PIT}/data"
		ar x --output "${PIT}" "${TMPDIR}/$FNAME" "$DATA"
		cd "${PIT}/data" || { echo "Couldn't munch any tartar in: ${PIT}/control" ; exit 1 ; }
		tar fx "${PIT}/$DATA"
		find "${PIT}/data" -name "*.?tf" -exec cp {} "$TARGET" \;
		# extract filelist with md5sum
		CONTROL="$(ar t "$TMPDIR/$FNAME" | grep '^control\.tar')"
		mkdir -p "${PIT}/control"
		ar x --output "${PIT}" "${TMPDIR}/$FNAME" "$CONTROL"
		cd "${PIT}/control" || { echo "Couldn't munch any tartar in: ${PIT}/control" ; exit 1 ; }
		tar xf "${PIT}/$CONTROL"
		mkdir -p "$FNTDATA/index" || { echo "Couldn't create index directory: $FNTDATA/index" ; exit 1 ; }
		sed -n 's/^\(.*\) .*\/\(.*tf$\)/\1 \2/p' "${PIT}/control/md5sums" > "$FNTDATA/index/$NAME"
	else
		echo "Can't verify md5sum!"
		exit 1
	fi
}

fnt_install() {
	if [ ! -f "${PACKAGES}" ]; then
		echo "Could not find ${PACKAGES}"
		echo "Please run ${BASH_SOURCE[0]} update"
		# could also just run itself with update...
		# but apt doesn't do that either :)
		exit 1
	fi
	if [ ! $# -eq 2 ]; then
		echo "No fontname supplied."
		echo "Example: ${BASH_SOURCE[0]} install agave"
		exit 1
	fi
	FNTMATCH=$2
	if [ ! -d "${TARGET}" ]; then
		mkdir -p "${TARGET}"
	fi
	# look for first font match
	p="$(unxz -c "${PACKAGES}" | awk '/^Package: (fonts-)?'"$FNTMATCH"'/ {gsub(/^Package: /,"");print;exit;}')"
	if [ -z "$p" ]; then
		q=$(pipe_download "$GINDEX/ofl/" |grep "a href" |sed 's,.*">,google-,;s,/.*,,' |grep "$FNTMATCH" | head -1)
		s=$(pipe_download "$GINDEX/apache/" |grep "a href" |sed 's,.*">,google-,;s,/.*,,' |grep "$FNTMATCH" | head -1)
		if [ -z "$q" ] && [ -z "$s" ]; then
			echo "Font \"$FNTMATCH\" not found"
			exit 1
		else
			FNTMATCH="${FNTMATCH#google-*}"
			echo "Installing google-${FNTMATCH}"
			# here comes the google web font installer part using grep '\..tf'
			pipe_download "$GINDEX/ofl/${FNTMATCH}/" |grep "a href" |grep "\..tf" |sed 's,.*tf.>,,' | sed 's,</..*,,' | while read -r f; do
			download "${GINDEX}/ofl/${FNTMATCH}/$f" "$TARGET/$f"
			${md5} "$TARGET/$f" | sed -n 's/^\(.*\) .*\/\(.*tf$\)/\1 \2/p' > "$FNTDATA/index/google-$FNTMATCH"
		done
		pipe_download "$GINDEX/apache/${FNTMATCH}/" |grep "a href" |grep "\..tf" |sed 's,.*tf.>,,' | sed 's,</..*,,' | while read -r f; do
		download "${GINDEX}/apache/${FNTMATCH}/$f" "$TARGET/$f"
		${md5} "$TARGET/$f" | sed -n 's/^\(.*\) .*\/\(.*tf$\)/\1 \2/p' > "$FNTDATA/index/google-$FNTMATCH"
	done
	exit 0
		fi
	fi
deb_handler "$p"
}

case "$s" in
	Darwin)
		#echo macOS
		check="curl brew otfinfo chafa"
		# otfinfo comes with lcdf-typetools
		i="brew"
		md5="md5sum"
		TARGET="$HOME/Library/Fonts/"
	;;
	Linux|GNU/kFreeBSD|GNU)
		#echo Linux
		check="curl chafa otfinfo"
		i="apt"
		md5="md5sum"
		TARGET="$HOME/.fonts/"
		if [ 0 -eq "$(id -u)" ]; then
			TARGET="/usr/local/share/fonts/"
		fi
	;;
	FreeBSD)
		#echo FreeBSD
		check="curl chafa otfinfo"
		i="pkg"
		md5="md5"
		TARGET="$HOME/.fonts/"
	;;
	OpenBSD)
		#echo OpenBSD
		check="curl chafa otfinfo"
		i="pkg_add"
		md5="md5"
		TARGET="$HOME/.local/share/fonts"
	;;
	Haiku)
		#echo Haiku OS
		check="curl"
		i="pkgman"
		TARGET="$HOME/config/non-packaged/data/fonts/"
	;;
	Windows)
		#echo Windows
		check="cmd.exe"
		i="ENOPKGMANAGER"
		TARGET="$USERPROFILE\\Fonts"
	;;
	*)
		echo "Please report $s to https://github.com/alexmyczko/fnt/issues"
		exit 1
	;;
esac

for a in $check; do
	if ! command -v "$a" &>/dev/null; then
		echo "$a not found, please use $i to install it."
		exit 1
	fi
done

case "$1" in
	help|-h)
		cat << 'EOF'
Syntax: fnt [ update | list | info | help ]
        fnt [ install | remove | preview | search ] font

update|-u  updates the font package index of debian sid
list|-l    lists installed fonts with glyphcount per font
info       information about how many fonts can be installed
help|-h    this help
install|-i install a font
remove|-r  remove a font
preview|-p preview a font
search|-s  search for font
EOF
	;;

	update|-u)
		echo Updating...
		mkdir -p "${FNTDATA}/index"
		if [ -f "${PACKAGES}" ]; then rm "${PACKAGES}"; fi
		download "$INDEX" "${PACKAGES}"
	;;

	info)
		echo "Information..."
		echo "Available Fonts: $(fnt search | wc -l)"
	;;

	list|-l)
		find "$TARGET" /usr/local/share/fonts -iname '*.?tf' 2>/dev/null | while read -r f; do
			echo "$(basename "${f}") [$(otfinfo -u "$f" 2>/dev/null | wc -l)]"
		done
	;;
	preview|-p)
		if [ $# -ne 2 ]; then
			echo "No fontname supplied."
			echo "Example: ${BASH_SOURCE[0]} preview agave"
			exit 1
		fi
		mkdir -p "${FNTDATA}/index"
		rm -f "${FNTDATA}/preview.png"
		PRINTED=
		if download "https://screenshots.debian.net/screenshot/fonts-$2" "${FNTDATA}/preview.png"; then
			# if we get nothing / "this picture is not available" pic
			if [ "$($md5 "${FNTDATA}/preview.png" | awk '{print$1}')" = "b5765b390157e36eaf721c8848a4b04d" ]; then
				if download "https://sid.ethz.ch/fonts/$2/preview.png" "${FNTDATA}/preview.png"; then
					chafa -c 240 -w 9 -O 9 -p on --symbols all "${FNTDATA}/preview.png" 2>/dev/null && PRINTED=1
				fi
			else
				chafa -c 240 -w 9 -O 9 -p on --symbols all "${FNTDATA}/preview.png" 2>/dev/null && PRINTED=1
			fi
		fi
		if [ "$PRINTED" != "1" ]; then
			echo "Couldn't retrieve a preview."
		fi
	;;
	install|-i)
		fnt_install "$@"
	;;
	remove|-r)
		echo "Removing..."
		echo "Feel free to send patches or dollars (see the sponsor link)"
	;;
	search|-s)
		if [ -f "${PACKAGES}" ]; then
			unxz -c "${PACKAGES}" | awk '/^Package: fonts-'"$2"'/ {gsub(/^Package: /,"");print;}'
		else
			echo "Skipping non-existent Packages cache. Consider running: ${BASH_SOURCE[0]} update" >&2
		fi
		if [[ "$(uname -s)" == "OpenBSD" ]]; then
			pipe_download "$GINDEX/ofl/" |ggrep "a href" |gsed 's,.*">,google-,;s,/.*,,;s,<$,,g' |ggrep -v "\.\.$" | awk "/$2/"
			pipe_download "$GINDEX/apache/" |ggrep "a href" |gsed 's,.*">,google-,;s,/.*,,;s,<$,,g' |ggrep -v "\.\.$" | awk "/$2/"
		else
			pipe_download "$GINDEX/ofl/" |grep "a href" |sed 's,.*">,google-,;s,/.*,,;s,<$,,g' |grep -v "\.\.$" | awk "/$2/"
			pipe_download "$GINDEX/apache/" |grep "a href" |sed 's,.*">,google-,;s,/.*,,;s,<$,,g' |grep -v "\.\.$" | awk "/$2/"
		fi
	;;
	moo)
		echo "This fnt does not have cow powers."
	;;
	wak)
		echo ' _()< wak wak'
		echo '(__)'
	;;
	quak)
		cat << 'EOF'
 _______
< QUAK? >
 -------
     \
      \
          oO)-.                       .-(Oo
         /__  _\                     /_  __\
         \  \(  |     ()~()         |  )/  /
          \__|\ |    (-___-)        | /|__/
          '  '--'    ==`-'==        '--'  '
EOF
	;;
	*)
		lolcat=$(command -v cat)
		if command -v lolcat>/dev/null; then lolcat=$(command -v lolcat); fi
		$lolcat << 'EOF'
   .d888
  d88P"           888
  888             888
.d88888 888888b. d888888
  888   888 "88b  888
  888   888  888  888
  888   888  888  Y88b.
  888   888  888   "Y888
EOF
	;;
esac
