.TH man 1 "12 Aug 2023" "1.1" "font downloader and manager"
.SH NAME
fnt \- download and install fonts
.SH SYNOPSIS
.TP
\fBfnt\fP \fIcommand\fP [\fIargument\fP]
.SH DESCRIPTION
This tool helps you to download vector fonts from
Debian sid, and Google Web Fonts.
.SH EXAMPLES
.TP
.I fnt update
update font index.
.TP
.I fnt search aga
search for fonts named aga.
.TP
.I fnt install agave
install the font called agave.
.TP
.I fnt preview agave
show a text-based preview of the font called agave.
.TP
.I fnt list
list installed fonts with glyphcount.
.SH SEE ALSO
birdfont(1),
bdf2sfd(1).
.SH BUGS
Please report to https://github.com/alexmyczko/fnt/issues
.SH AUTHOR
Alex Myczko <alex@aiei.ch>
.SH INTERNET
https://github.com/alexmyczko/fnt
